export const players = [
  {
    name: "Didier Drogba",
    nationality: "Ivory Coast",
    position: "Striker",
    clubs: ["Chelsea", "Galatasaray", "Marseille"],
    played_in_turkey: "2013-2014",
    fun_fact: "Scored against Fenerbahçe in the Intercontinental Derby.",
  },
  {
    name: "Robin van Persie",
    nationality: "Netherlands",
    position: "Striker",
    clubs: ["Arsenal", "Manchester United", "Fenerbahçe"],
    played_in_turkey: "2015-2018",
    fun_fact: "Won the Premier League Golden Boot twice.",
  },
  {
    name: "Wesley Sneijder",
    nationality: "Netherlands",
    position: "Midfielder",
    clubs: ["Real Madrid", "Inter Milan", "Galatasaray"],
    played_in_turkey: "2013-2017",
    fun_fact: "Won the treble with Inter Milan in 2010.",
  },
  {
    name: "Ricardo Quaresma",
    nationality: "Portugal",
    position: "Winger",
    clubs: ["Porto", "Besiktas", "Barcelona", "Inter Milan"],
    played_in_turkey: "2010-2013, 2015-2019",
    fun_fact: "Famous for his trivela shots.",
  },
  {
    name: "Mesut Özil",
    nationality: "Germany",
    position: "Midfielder",
    clubs: ["Real Madrid", "Arsenal", "Fenerbahçe", "Başakşehir"],
    played_in_turkey: "2021-2023",
    fun_fact: "Won the World Cup with Germany in 2014.",
  },
  {
    name: "Mário Jardel",
    nationality: "Brazil",
    position: "Striker",
    clubs: ["Porto", "Galatasaray", "Sporting CP"],
    played_in_turkey: "2000-2001",
    fun_fact: "Won the European Golden Shoe while at Galatasaray.",
  },
  {
    name: "Roberto Carlos",
    nationality: "Brazil",
    position: "Left Back",
    clubs: ["Real Madrid", "Fenerbahçe"],
    played_in_turkey: "2007-2009",
    fun_fact: "Known for one of the greatest free kicks in football history.",
  },
  {
    name: "Pepe",
    nationality: "Portugal",
    position: "Defender",
    clubs: ["Real Madrid", "Besiktas", "Porto"],
    played_in_turkey: "2017-2019",
    fun_fact: "Won 3 UEFA Champions League titles with Real Madrid.",
  },
  {
    name: "Emmanuel Adebayor",
    nationality: "Togo",
    position: "Striker",
    clubs: ["Arsenal", "Manchester City", "Real Madrid", "Başakşehir"],
    played_in_turkey: "2017-2019",
    fun_fact: "Scored a hat-trick for Başakşehir against Galatasaray.",
  },
  {
    name: "Samuel Eto'o",
    nationality: "Cameroon",
    position: "Striker",
    clubs: ["Barcelona", "Inter Milan", "Antalyaspor", "Konyaspor"],
    played_in_turkey: "2015-2019",
    fun_fact: "Won the Champions League with two different clubs.",
  },
];
